theme: fullwidth
title: Colorly
author: Adam Graham
author_url: https://github.com/adamgraham
github_url: https://github.com/adamgraham/colorly
copyright: Copyright (c) 2019 Adam Graham
readme: README.md
source_directory: ./Colorly
clean: true
skip_undocumented: true
